use Northwind
-- 1 - Write a query to retrieve the names of all products that have been ordered more than 50 time.
select * from [Order Details]
select * from Products

select ProductName , count(ProductName) as count from Products as pd
left join [Order Details] as od
on (od.ProductID = pd.ProductID)
group by ProductName 
having count(ProductName) >50


-- 2 - Write a query to retrieve the names of all products that have been ordered at least once.
select distinct ProductName   from Products as pd
left join [Order Details] as od
on (od.ProductID = pd.ProductID)

-- 3 - Create a view that shows the total revenue generated by each category.

CREATE VIEW CategoryRevenue AS
SELECT c.CategoryName, SUM(od.UnitPrice * od.Quantity * (1 - od.Discount)) AS TotalRevenue
FROM Categories c
JOIN Products p ON c.CategoryID = p.CategoryID
JOIN [Order Details] od ON p.ProductID = od.ProductID
GROUP BY c.CategoryName;
