use northwind

/* Write a query to retrieve the names of all products that have been ordered more than 50 time.*/
SELECT ProductName,ProductID,(SELECT COUNT(*)  
     FROM [Order Details] 
     WHERE ProductID=Products.ProductID) NoOfOrders
FROM Products 
WHERE 50 < 
    (SELECT COUNT(*) 
     FROM [Order Details] 
     WHERE ProductID=Products.ProductID);
/* Write a query to retrieve the names of all products that have been ordered at least once.*/
SELECT ProductName,(SELECT COUNT(*)  
     FROM [Order Details] 
     WHERE ProductID=Products.ProductID) NoOfOrders
FROM Products 
WHERE 1 < 
    (SELECT COUNT(*) 
     FROM [Order Details] 
     WHERE ProductID=Products.ProductID);
select * from Products
	 
/* Create a view that shows the total revenue generated by each category.
*/
select CategoryName,sum([Order Details Extended].unitPrice*Quantity) as TotalValue from [Order Details Extended] 
inner join Products
on [Order Details Extended].ProductID=Products.ProductID 
inner join Categories on Categories.CategoryID=Products.CategoryID
group by CategoryName


