--TASK 6
--1 - Write a query to retrieve the names of all products that have been ordered more than 50 time.

SELECT ProductName , UnitsOnOrder as orders
FROM Products
WHERE unitsonorder in (SELECT UnitsOnOrder FROM Products WHERE UnitsOnOrder > 50 )
ORDER BY UnitsOnOrder desc;

--2  Write a query to retrieve the names of all products that have been ordered at least once.

SELECT ProductName , UnitsOnOrder as orders
FROM Products
WHERE UnitsOnOrder in (SELECT UnitsOnOrder FROM Products WHERE UnitsOnOrder > 0 )
ORDER BY UnitsOnOrder desc;

--3 Create a view that shows the total revenue  generated by each category.


SELECT c.CategoryName , sum(od.Quantity*od.Unitprice) AS TOTAL_SALES
from Categories as c
INNER JOIN products as p on p.categoryid = c.categoryid
INNER JOIN [Order Details] as od on od.ProductID = p.ProductID
GROUP BY c.CategoryName;

