use Northwind

--1 - Write a query to retrieve the names of all products that have been ordered more than 50 time.
SELECT ProductName
FROM Products
WHERE ProductID IN (
  SELECT ProductID
  FROM [Order Details]
  GROUP BY ProductID
  HAVING COUNT(*) > 50
);

--2. Write a query to retrieve the names of all products that have been ordered at least once.
SELECT ProductName
FROM Products
WHERE ProductID IN (
  SELECT ProductID
  FROM [Order Details]
  GROUP BY ProductID
);

select*from Categories

 --3. Create a view that shows the total revenue generated by each category.
 --felhal i was unable to calculate revenue 
 Create view Revenue_by_category as 
 select* from products as p
 inner join Categories as c on c.CategoryID=p.CategoryID