--1 - Write a query to retrieve the names of all products that have been ordered more than 50 time.
Select p.ProductName, p.ProductID from Products p
Where 50 < (Select Count(od.ProductID) from [Order Details] od where od.ProductID = p.ProductID)

--2 - Write a query to retrieve the names of all products that have been ordered at least once.
Select p.ProductName, p.ProductID from Products p
Where p.ProductID in (Select Distinct od.ProductID from [Order Details] od)


--3 - Create a view that shows the total revenue generated by each category.
Create view rev_generated_by_category
as
Select c.CategoryName, (SUM(od.UnitPrice * od.Quantity)) from [Order Details] od
JOIN Products p ON p.ProductID = od.ProductID
JOIN Categories c ON c.CategoryID = p.CategoryID
Group By c.CategoryName




