USE northwind

--Write a query to retrieve the names of all products that have been ordered more than 50 time.

SELECT ProductName 
FROM Products 
WHERE  ProductID IN (SELECT ProductID
FROM [Order Details]
GROUP BY ProductID
HAVING SUM(Quantity) > 50);

--Write a query to retrieve the names of all products that have been ordered at least once.

SELECT ProductName 
FROM Products 
WHERE  ProductID IN (SELECT ProductID
FROM [Order Details]
GROUP BY ProductID
HAVING SUM(Quantity) > 0);

--Create a view that shows the total revenue generated by each category.

--Create view
CREATE VIEW CategoryRevenue AS
SELECT c.CategoryName, SUM(od.UnitPrice * od.Quantity * (1 - od.Discount)) AS TotalRevenue
FROM Categories c
INNER JOIN Products p ON c.CategoryID = p.CategoryID
INNER JOIN [Order Details] od ON p.ProductID = od.ProductID
GROUP BY c.CategoryName;

SELECT * FROM CategoryRevenue;

--DROP VIEW
DROP VIEW CategoryRevenue;

