/*ordered more then 50 times*/
SELECT Products.ProductName
FROM Products
JOIN OrderDetails ON Products.ProductID = OrderDetails.ProductID
GROUP BY Products.ProductName
HAVING SUM(OrderDetails.Quantity) > 50;

/*all products that have been ordered at least once*/
SELECT Products.ProductName
FROM Products
JOIN OrderDetails ON Products.ProductID = OrderDetails.ProductID
GROUP BY Products.ProductName
HAVING SUM(OrderDetails.Quantity) >= 1;


/*To create a view that shows the total revenue generated by each category*/
CREATE VIEW TotalRevenueByCategory AS
SELECT Categories.CategoryName, SUM(OrderDetails.UnitPrice * OrderDetails.Quantity) AS TotalRevenue
FROM Categories
JOIN Products ON Categories.CategoryID = Products.CategoryID
JOIN OrderDetails ON Products.ProductID = OrderDetails.ProductID
GROUP BY Categories.CategoryName;
	