--Week 3 Task 6


--1 Write a query to retrieve the names of all products that have been ordered more than 50 time.


select  ProductName , UnitsOnOrder  as orders
from Products
where unitsonorder in (select UnitsOnOrder from Products where UnitsOnOrder > 40 )
order by UnitsOnOrder asc;


--2 Write a query to retrieve the names of all products that have been ordered at least once.


select ProductName , UnitsOnOrder as orders
from Products
where unitsonorder in (select UnitsOnOrder from Products where UnitsOnOrder >= 1 )
order by UnitsOnOrder asc;


--3 - Create a view that shows the total revenue generated by each category.


select c.CategoryName , sum(od.Quantity*od.Unitprice) as totalsales
from Categories as c
inner join products as p on p.categoryid = c.categoryid
inner join [Order Details] as od on od.ProductID = p.ProductID
GROUP BY c.CategoryName;