/*********************** task # 6 ***************/

/***Create a view that shows the total revenue generated by each category.*******/

CREATE VIEW Revenue
AS
SELECT c.CategoryName, SUM(od.UnitPrice * Od.Quantity * (1 - Od.Discount)) AS TotalRevenue
FROM Categories c INNER JOIN Products p ON 
c.CategoryID = p.CategoryID INNER JOIN [Order Details] od ON p.ProductID = Od.ProductID
GROUP BY c.CategoryName


SELECT * FROM Revenue

/**********Write a query to retrieve the names of all products that have been ordered more than 50 time.***********/

SELECT ProductName FROM Products p
INNER JOIN [Order Details] od ON p.ProductID = od.ProductID
GROUP BY p.ProductName 
HAVING SUM(Quantity) > 50

/*****Write a query to retrieve the names of all products that have been ordered at least once.********/


SELECT ProductName FROM Products p 
INNER JOIN [Order Details] od ON p.ProductID = od.ProductID
