USE Northwind;
-- Write a query to retrieve the names of all products that have been ordered more than 50 time
SELECT ProductID, ProductName
FROM Products 
WHERE ProductID IN (
    SELECT ProductID 
    FROM [Order Details] 
    GROUP BY ProductID 
    HAVING COUNT(*) > 50
);
-- Write a query to retrieve the names of all products that have been ordered at least once.
SELECT DISTINCT Products.ProductName
FROM Products
INNER JOIN [Order Details]
ON Products.ProductID = [Order Details].ProductID; 

-- Create a view that shows the total revenue generated by each category.
GO
CREATE VIEW [Revenue_by_Category] AS
SELECT Categories.CategoryName, SUM([Order Details].UnitPrice * [Order Details].Quantity) AS Generated_Revenue
FROM Categories
INNER JOIN Products 
ON Categories.CategoryID = Products.CategoryID
INNER JOIN [Order Details] 
ON Products.ProductID = [Order Details].ProductID
GROUP BY Categories.CategoryName;

SELECT * 
FROM [Revenue_by_Category]