name = "Daniyal Ahmed"
print(len(name))
print(name[3])
print(name.index("D"))
print(name.replace("Daniyal", "Haroon"))
print(name.lower())
print(name.islower())
print(name.isupper())
print(name.upper())
print(name.upper().isupper())
print(name.lower().islower())
print(name + " is cool")
print("Daniyal\nAhmed")
print("Daniyal\"Ahmed")