--Task # 6

--1 Write a query to retrieve the names of all products that have been ordered more than 50 time.

SELECT ProductName from Products p INNER JOIN [Order Details] od ON p.ProductID = od.ProductID
GROUP BY p.ProductName having SUM(Quantity) > 50

--2- Write a query to retrieve the names of all products that have been ordered at least once.
select * from [Order Details]
select * from Orders

select ProductName FROM Products p INNER JOIN [Order Details] od ON p.ProductID = od.ProductID

--3 - Create a view that shows the total revenue generated by each category.

CREATE VIEW CategoryRevenue
AS
Select c.CategoryName, SUM(od.UnitPrice * Od.Quantity * (1 - Od.Discount)) AS TotalRevenue
From Categories c INNER JOIN Products p ON c.CategoryID = p.CategoryID INNER JOIN [Order Details] od ON p.ProductID = Od.ProductID
GROUP BY c.CategoryName

SELECT * FROM CategoryRevenue