-- Write a query to retrieve the names of all products that have been ordered more than 50 time.

select ProductName from Products
where ProductID in
(select ProductID from [Order Details] 
 group by ProductID
 having sum(Quantity) > 50)
 ORDER BY ProductName;


-- Write a query to retrieve the names of all products that have been ordered at least once.
SELECT ProductName
FROM Products
WHERE ProductID IN (
    SELECT DISTINCT ProductID
    FROM [Order Details]
);


-- Create a view that shows the total revenue generated by each category

CREATE VIEW category_revenue AS
SELECT c.CategoryName, SUM(od.UnitPrice * od.Quantity * (1 - od.Discount)) AS TotalRevenue
FROM Categories c
JOIN Products p ON c.CategoryID = p.CategoryID
JOIN [Order Details] od ON p.ProductID = od.ProductID
GROUP BY c.CategoryName
ORDER BY TotalRevenue DESC;