/* Practicing Constraint 
NOT NULL, UNIQUE, DEFAULT, CHECK, PRIMARY KEY and FORIEGN KEY
-------------------------------
 Tables
creating table, altering it and deleting table in the end*/

CREATE TABLE STUDENT
(STD_ID int NOT NULL PRIMARY KEY,
STD_NAME varchar(50) NOT NULL,
AGE int NOT NULL,
TRACK varchar(50),
MOBILE_PHONE int NOT NULL UNIQUE,
GENDER char (1) CHECK (GENDER LIKE 'M' OR GENDER LIKE 'F'),
); 

INSERT INTO STUDENT VALUES
(1001,'AHTISHAM BHAI', 25, 'DATA ENGINEER', 0311,'M'),
(1002,'UZMAN ALI', 23, 'DATA ENGINEER', 03131, 'M'),
(1003,'ZULFI BUKHARI', 43, 'DATA ENGINEER', 2131321, 'F');

SELECT * FROM STUDENT

--ALTER TABLE STUDENT
--DROP GENDER varchar(50)

--DROP TABLE STUDENT