use Northwind;
--Write a query to retrieve the names of all products that have been ordered more than 50 time
SELECT Products.ProductName
FROM products 
INNER JOIN orders ON products.ProductID = orders.productID
HAVING COUNT(orders.OrderID) > 50;


---Write a query to retrieve the names of all products that have been ordered at least once
SELECT Products.ProductName 
FROM products 
INNER JOIN orders ON Products.ProductID = orders.ProductID 
GROUP BY Products.ProductID;


---Create a view that shows the total revenue generated by each category

--CREATE VIEW [category_revenue] AS
SELECT Categories.CategoryName, SUM(Products.UnitsInStock * Products.QuantityPerUnit) AS revenue
FROM categories 
INNER JOIN products ON Categories.CategoryID = Products.CategoryID
INNER JOIN orders ON Products.ProductID = orders.Product
GROUP BY Categories.CategoryID;