USE northwind

SELECT * FROM [Order Details]
WHERE Quantity IS NULL
ORDER BY ProductID

SELECT * FROM Products
SELECT * FROM [Order Details]
--1 - Write a query to retrieve the names of all products that have been ordered more than 50 time.

SELECT ProductName
FROM Products
WHERE ProductID IN (SELECT ProductID
                    FROM [Order Details]
                    GROUP BY ProductID
                    HAVING COUNT(*)>50);


--2 - Write a query to retrieve the names of all products that have been ordered at least once.

SELECT ProductName
FROM Products
WHERE ProductID IN (SELECT ProductID
                    FROM [Order Details]
                    GROUP BY ProductID
                    HAVING COUNT(*)>=1);


--3 - Create a view that shows the total revenue generated by each category.

CREATE VIEW [Total Revenue By Each Category] AS
SELECT C.CategoryName,SUM(OD.UnitPrice*OD.Quantity) AS Revenue
FROM Categories C
INNER JOIN Products P ON P.CategoryID=C.CategoryID
INNER JOIN [Order Details] OD ON OD.ProductID = P.ProductID
GROUP BY C.CategoryName



SELECT *
FROM [Total Revenue By Each Category]

