-- Write a query to retrieve the names of all products that have been ordered more than 50 time.

select *
from [production].[products];
select *
from [sales].[order_items];
select *
from [sales].[orders];


SELECT p.product_name
FROM [production].products p
    JOIN [sales].order_items o ON o.product_id = p.product_id
GROUP BY p.product_name
HAVING COUNT(*) > 50;


-- 2 - Write a query to retrieve the names of all products that have been ordered at least once.
select p.product_name
from production.products as p
    join sales.order_items as o
    on p.product_id = o.product_id
GROUP by product_name
having COUNT(*) > 1

-- 3 - Create a view that shows the total revenue generated by each category.
select *
from sales.order_items


drop view if EXISTS category_count

create view category_count
as
    select SUM(sales.order_items.list_price) as Sum_of_Category, COUNT(category_id) as Category_count
    from production.products
        join sales.order_items
        on production.products.product_id = sales.order_items.product_id
    group by production.products.category_id, sales.order_items.list_price;


select *
from category_count