use NORTHWND;
/* 1 - Write a query to retrieve the names of all products that have been ordered more than 50 time. */

Select productID, ProductName from Products where ProductID IN (

select count(*) as Cont from [Order Details] group by ProductID having COUNT(*) > 50 ) ;
/* 2 - Write a query to retrieve the names of all products that have been ordered at least once. */

Select productID, ProductName from Products where ProductID IN (

select count(*) as Cont from [Order Details] group by ProductID having COUNT(*) > 0 ) ;

/* 3 - Create a view that shows the total revenue generated by each category. */

select (P.UnitPrice *  P.UnitsOnOrder), 
( Select CategoryName from Categories C where P.CategoryID = C.categoryID )
as Category_name from Products P where (P.UnitPrice *  P.UnitsOnOrder) > 0;