--Write a query to retrieve the names of all products that have been ordered more than 50 time.
select p.ProductName
from Products p
where 
    (select count(o.OrderID) as OrderCount
     from [Order Details] od
     inner join Orders o on od.OrderID = o.OrderID
     where od.ProductID = p.ProductID
    ) > 50;
--Write a query to retrieve the names of all products that have been ordered at least once.
SELECT ProductName
FROM Products
WHERE ProductID IN (
    SELECT DISTINCT ProductID
    FROM [Order Details]
);

--Create a view that shows the total revenue generated by each category.
create view CategoryReveune as
select c.CategoryName, (select sum(od.UnitPrice * od.Quantity) AS TotalRevenue from [Order Details] od join Products p on  od.ProductID=p.ProductID where p.CategoryID=c.CategoryID) as TotalReveune from Categories c;

select * from CategoryReveune

