USE northwind;

--Q1. Write a query to retrieve the names of all products that have been ordered more 
-- than 50 time.

SELECT P.ProductName
FROM Products P
INNER JOIN [Order Details] O
	ON P.ProductID = O.ProductID
GROUP BY P.ProductName
HAVING SUM(O.Quantity) >50


--Q2. Write a query to retrieve the names of all products that have been ordered at 
-- least once?

SELECT P.ProductName
FROM Products P
INNER JOIN [Order Details] O
	ON P.ProductID = O.ProductID
GROUP BY P.ProductName
HAVING COUNT(*) <> 0



--Q3. Create a view that shows the total revenue generated by each category?

CREATE VIEW VIEW_Total_Revenue
AS
SELECT C.CategoryName, SUM(O.UnitPrice * O.Quantity *(1 - O.Discount)) AS REVENUE
FROM Categories C
INNER JOIN Products P
	ON C.CategoryID = P.CategoryID
INNER JOIN [Order Details] O
	ON P.ProductID = O.ProductID
GROUP BY C.CategoryName

-- Calling View
SELECT * FROM VIEW_Total_Revenue